# learning recipe
lr: 0.001
noise_dim: 100
epoch: 100
batch_size: 32
l_gp: 10
optimizer: 'adam'

# others
device: 'cuda'
save_path: 'inverted_img'
target_img: 'source.jpg'
target_shape: 64
G_weight: 'generator.pt'