# learning recipe
lr: 0.001
noise_dim: 512
iter: 1000

# others
device: 'cuda'
save_path: 'results/inverted_12_img'
save_target: 'results/target_img'
target_img: 'synthesize/20_avg.jpg'
target_shape: 512
G_weight: 'pgan'